// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// require("dotenv-flow").config();
// import "dotenv-flow/config";
// import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
